dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose -f local.yml build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose -f local.yml run --rm django python manage.py migrate
        - docker-compose -f local.yml up -d
      script:
        - "docker-compose -f local.yml run django pytest --cov-report term --cov=."
        - "docker-compose -f local.yml run django sphinx-build -b html ./docs /.docs/_build"
      after_failure:
        - docker-compose -f local.yml logs
      after_success:
        - docker-compose -f local.yml exec django pip3 install codecov
        - ci_env="bash <(curl -s https://codecov.io/env)"
        - ci_post_cov="bash <(curl -s https://codecov.io/bash)"
        - docker-compose run -t django /bin/bash -c "$ci_env && pytest && coverage run -m pytest && $ci_post_cov"
